Upgrade to hapi 17
firstandthird/hapi-oppsy pull request #5
Opened 2017-12-21 17:58 UTC by dawnerd

2017-12-21 18:54 UTC, jgallen23 requested changes

2017-12-21 18:54 UTC, jgallen23 commented on package.json
> +    "hapi-logr": "^4.0.0",
can remove these now

2017-12-21 18:54 UTC, jgallen23 commented on package.json
> +    "oppsy": "2.0.0"
maybe ^2.0.0?

2017-12-21 18:56 UTC, jgallen23 requested changes

2017-12-21 18:56 UTC, jgallen23 commented on example/index.js
> +      h.redirect('https://google.com');
need to return

2017-12-22 07:56 UTC, dawnerd commented on package.json
> +    "hapi-logr": "^4.0.0",
The example script uses it

2017-12-27 19:32 UTC, merged